// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpseeUNLQ3JC5Wff7JAn7tOXPnyiVHJYw',
    appId: '1:104753424624:web:89b8f96d2bb7d16a30fa35',
    messagingSenderId: '104753424624',
    projectId: 'wedding-app-60fa9',
    authDomain: 'wedding-app-60fa9.firebaseapp.com',
    databaseURL: 'https://wedding-app-60fa9-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-app-60fa9.appspot.com',
    measurementId: 'G-9FWPYBZHES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfLfkiEa7WiD7iCAFES7JYzHTr_Ja9oQs',
    appId: '1:104753424624:android:28be19629b9f4e8230fa35',
    messagingSenderId: '104753424624',
    projectId: 'wedding-app-60fa9',
    databaseURL: 'https://wedding-app-60fa9-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-app-60fa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSd0GpCUfDHhrQStLMSYwujAapgNEAmS8',
    appId: '1:104753424624:ios:9dbc3cd4f362e72d30fa35',
    messagingSenderId: '104753424624',
    projectId: 'wedding-app-60fa9',
    databaseURL: 'https://wedding-app-60fa9-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-app-60fa9.appspot.com',
    iosClientId: '104753424624-41u1coaq7n2n2saj347ekjk2j2fap1ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.wedding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSd0GpCUfDHhrQStLMSYwujAapgNEAmS8',
    appId: '1:104753424624:ios:5da272acc3e17f5330fa35',
    messagingSenderId: '104753424624',
    projectId: 'wedding-app-60fa9',
    databaseURL: 'https://wedding-app-60fa9-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-app-60fa9.appspot.com',
    iosClientId: '104753424624-363kh15cg4golijf8tht2jpmd5njc1c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wedding.RunnerTests',
  );
}
